### ISSUE TITLE
 LasercutJigsaw instance has no attribute 'unittouu'

### ISSUE THREAD

**Issue by nipundavid** [Neon22/inkscape-jigsaw#5]
http://tuts.ahninniah.graphics/content/images/2014/May/how-to-make-a-jigsaw-puzzle-with-gimp-and-inkscape.pdf

I have installed the script using info at - http://wiki.inkscape.org/wiki/index.php/Script_extensions#Installing

Traceback (most recent call last):

  File "Lasercut-jigsaw.py", line 879, in <module>

    e.affect()

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

    self.effect()

  File "Lasercut-jigsaw.py", line 798, in effect

    docW = self.unittouu(self.document.getroot().get('width'))

AttributeError: LasercutJigsaw instance has no attribute 'unittouu'
![ink](https://cloud.githubusercontent.com/assets/2108309/9035202/6a2c7332-39f3-11e5-83ac-0c6fe96d377d.png)

**Comment by Neon22** [comment]
you need to update to inkscape 0.91.
They changed syntax between 0.48 and 0.91.
this plugin is now designed to work in 0.91
Cheers...

**Comment by nipundavid** [comment]
Great, I think I should update my dev and designing tools more often He He :laughing: 

Sorry to bother you.

**Comment by itsanov** [comment]
I know, this thread is pretty old, but in case somebody else is using 0.48 like me, all you have to do to make it running is to replace
`docW = self.unittouu(self.document.getroot().get('width'))`
with
`docW = inkex.unittouu(self.document.getroot().get('width'))`

**Comment by Ryujin** [comment]
Oh man, **_thanks_**, @itsanov !  That's all it took to get the JTech Photonics laser tool working on this old machine.
